source, target  = input("Enter file name and target: ").split()
sf =  open(source, "r")
tf = open(target, "w")
s = sf.read()
while s != "" :
    tf.write(s)
    s = sf.read()
sf.close()
tf.close()
tf = open(target, "r")
print("The contents of target file:")
s = tf.read()
while s != "" :
    print(s, end = "")
    s = tf.read()
tf.close()
