import pandas as pds
file = ('d:/Student.xlsx')
data = pds.read_excel(file)
print("All data is : ")
print("----------------")
print(data)
print("----------------")
print("Sum rows of data : ")
print("----------------")
print(data.loc[[1, 2, 3], ['Name','StNo']])
print("----------------")
print("All rows with two columns: ")
print(data.loc[:, ['Name','Grade']])
print("----------------")
print("Median is : ", end = "")
print(data['Grade'].median())
print("Mean is : ", end = "")
print(data['Grade'].mean())
